2023-11-10 01:09:35,023 - WARNING - django.request - Bad Request: /api/v1/backend/login
2023-11-10 01:09:54,785 - INFO - climatewavers - argument of type 'NoneType' is not iterable
2023-11-10 01:09:54,787 - WARNING - django.request - Unauthorized: /api/v1/backend/login
2023-11-10 01:10:42,738 - INFO - climatewavers - argument of type 'NoneType' is not iterable
2023-11-10 01:10:42,740 - WARNING - django.request - Unauthorized: /api/v1/backend/login
2023-11-10 01:19:35,667 - INFO - django.utils.autoreload - /home/olagold-hackxx/Projects/Portfolio/backend/climate_wavers/views.py changed, reloading.
2023-11-10 01:43:36,026 - ERROR - climatewavers - User matching query does not exist.
2023-11-10 01:44:12,067 - ERROR - climatewavers - User matching query does not exist.
2023-11-10 01:45:43,549 - ERROR - climatewavers - User matching query does not exist.
2023-11-10 01:46:09,241 - ERROR - climatewavers - User matching query does not exist.
2023-11-10 01:46:09,242 - WARNING - django.request - Bad Request: /api/v1/backend/de8650c3f0bf/verify
2023-11-10 01:49:26,134 - INFO - django.utils.autoreload - /home/olagold-hackxx/Projects/Portfolio/backend/climate_wavers/views.py changed, reloading.
2023-11-10 01:50:15,260 - INFO - django.utils.autoreload - /home/olagold-hackxx/Projects/Portfolio/backend/climate_wavers/views.py changed, reloading.
2023-11-10 01:51:41,305 - ERROR - climatewavers - Field name `is_staff` is not valid for model `User`.
2023-11-10 01:52:28,998 - INFO - django.utils.autoreload - /home/olagold-hackxx/Projects/Portfolio/backend/climate_wavers/views.py changed, reloading.
2023-11-10 01:52:35,819 - ERROR - climatewavers - Field name `is_staff` is not valid for model `User`.
2023-11-10 01:53:04,250 - INFO - django.utils.autoreload - /home/olagold-hackxx/Projects/Portfolio/backend/climate_wavers/views.py changed, reloading.
2023-11-10 01:53:10,287 - ERROR - climatewavers - Field name `is_staff` is not valid for model `User`.
2023-11-10 01:55:26,128 - INFO - django.utils.autoreload - /home/olagold-hackxx/Projects/Portfolio/backend/climate_wavers/views.py changed, reloading.
2023-11-10 01:55:35,427 - ERROR - climatewavers - Field name `is_staff` is not valid for model `User`.
2023-11-10 01:56:00,481 - INFO - django.utils.autoreload - /home/olagold-hackxx/Projects/Portfolio/backend/climate_wavers/serializers.py changed, reloading.
2023-11-10 01:56:18,709 - ERROR - climatewavers - Field name `is_staff` is not valid for model `User`.
2023-11-10 01:57:51,328 - INFO - django.utils.autoreload - /home/olagold-hackxx/Projects/Portfolio/backend/climate_wavers/views.py changed, reloading.
2023-11-10 01:57:58,507 - ERROR - climatewavers - Field name `is_staff` is not valid for model `User`.
2023-11-10 01:59:07,455 - INFO - django.utils.autoreload - /home/olagold-hackxx/Projects/Portfolio/backend/climate_wavers/serializers.py changed, reloading.
2023-11-10 01:59:27,101 - ERROR - climatewavers - Object of type RefreshToken is not JSON serializable
2023-11-10 01:59:50,162 - INFO - django.utils.autoreload - /home/olagold-hackxx/Projects/Portfolio/backend/climate_wavers/views.py changed, reloading.
2023-11-13 08:55:54,245 - INFO - climatewavers - User matching query does not exist.
2023-11-13 08:55:54,251 - WARNING - django.request - Unauthorized: /api/v1/backend/login
2023-11-13 08:57:43,081 - WARNING - django.request - Bad Request: /api/v1/backend/register
2023-11-13 09:00:03,313 - ERROR - django.request - Internal Server Error: /api/v1/backend/profile
Traceback (most recent call last):
  File "/home/olagold-hackxx/Projects/Portfolio/backend/climate_wavers/middlewares.py", line 31, in __call__
    token = CustomToken.objects.get(refresh_token=refresh_token)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/db/models/query.py", line 435, in get
    raise self.model.DoesNotExist(
climate_wavers.models.CustomToken.DoesNotExist: CustomToken matching query does not exist.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/olagold-hackxx/Projects/Portfolio/backend/climate_wavers/middlewares.py", line 59, in __call__
    elif refresh_token and (token != "") and (refresh_token != token.refresh_token):
AttributeError: 'str' object has no attribute 'refresh_token'
2023-11-13 09:01:34,383 - INFO - django.utils.autoreload - /home/olagold-hackxx/Projects/Portfolio/backend/climate_wavers/middlewares.py changed, reloading.
2023-11-13 09:05:48,871 - INFO - django.utils.autoreload - /home/olagold-hackxx/Projects/Portfolio/backend/climate_wavers/middlewares.py changed, reloading.
2023-11-13 09:05:56,082 - WARNING - django.request - Unauthorized: /api/v1/backend/profile
2023-11-13 09:06:16,687 - WARNING - django.request - Unauthorized: /api/v1/backend/profile
2023-11-13 09:06:31,339 - INFO - django.utils.autoreload - /home/olagold-hackxx/Projects/Portfolio/backend/climate_wavers/middlewares.py changed, reloading.
2023-11-13 09:07:04,030 - WARNING - django.request - Unauthorized: /api/v1/backend/profile
2023-11-13 09:09:09,604 - INFO - django.utils.autoreload - /home/olagold-hackxx/Projects/Portfolio/backend/climate_wavers/middlewares.py changed, reloading.
2023-11-13 09:09:15,417 - WARNING - django.request - Unauthorized: /api/v1/backend/profile
2023-11-13 09:09:32,255 - INFO - django.utils.autoreload - /home/olagold-hackxx/Projects/Portfolio/backend/climate_wavers/middlewares.py changed, reloading.
2023-11-13 09:09:39,291 - WARNING - django.request - Unauthorized: /api/v1/backend/profile
2023-11-13 09:10:51,690 - WARNING - django.request - Unauthorized: /api/v1/backend/
2023-11-13 09:11:38,742 - INFO - django.utils.autoreload - /home/olagold-hackxx/Projects/Portfolio/backend/climate_wavers/middlewares.py changed, reloading.
2023-11-13 09:11:42,555 - WARNING - django.request - Forbidden: /api/v1/backend/
2023-11-13 09:11:54,960 - WARNING - django.request - Forbidden: /api/v1/backend/
2023-11-13 09:13:09,311 - WARNING - django.request - Forbidden: /api/v1/backend/
2023-11-13 09:14:01,716 - WARNING - django.request - Forbidden: /api/v1/backend/
2023-11-13 09:14:34,453 - WARNING - django.request - Not Found: /api/v1/backend/profile
2023-11-13 09:14:44,101 - WARNING - django.request - Forbidden: /api/v1/backend/test/profile
2023-11-13 09:15:20,567 - INFO - django.utils.autoreload - /home/olagold-hackxx/Projects/Portfolio/backend/climate_wavers/urls.py changed, reloading.
2023-11-13 09:15:24,787 - WARNING - django.request - Forbidden: /api/v1/backend/test/profile
2023-11-13 09:15:27,165 - WARNING - django.request - Forbidden: /api/v1/backend/test/profile
2023-11-13 09:15:32,054 - INFO - django.utils.autoreload - /home/olagold-hackxx/Projects/Portfolio/backend/climate_wavers/urls.py changed, reloading.
2023-11-13 09:15:39,190 - WARNING - django.request - Forbidden: /api/v1/backend/test/profile
2023-11-13 09:15:41,858 - WARNING - django.request - Forbidden: /api/v1/backend/test/profile
2023-11-13 09:17:05,613 - WARNING - django.request - Forbidden: /api/v1/backend/
2023-11-13 09:17:21,535 - WARNING - django.request - Forbidden: /api/v1/backend/
2023-11-13 09:17:39,891 - INFO - django.utils.autoreload - /home/olagold-hackxx/Projects/Portfolio/backend/climate_wavers/middlewares.py changed, reloading.
2023-11-13 09:17:45,403 - WARNING - django.request - Forbidden: /api/v1/backend/
2023-11-13 09:17:52,485 - INFO - django.utils.autoreload - /home/olagold-hackxx/Projects/Portfolio/backend/climate_wavers/middlewares.py changed, reloading.
2023-11-13 09:18:20,531 - INFO - django.utils.autoreload - /home/olagold-hackxx/Projects/Portfolio/backend/climate_wavers/middlewares.py changed, reloading.
2023-11-13 09:18:24,541 - WARNING - django.request - Forbidden: /api/v1/backend/
2023-11-13 09:18:41,839 - WARNING - django.request - Forbidden: /api/v1/backend/
2023-11-13 09:18:53,797 - WARNING - django.request - Forbidden: /api/v1/backend/community
2023-11-13 09:18:56,918 - WARNING - django.request - Forbidden: /api/v1/backend/community
2023-11-13 09:19:10,160 - WARNING - django.request - Forbidden: /api/v1/backend/community
2023-11-13 09:19:44,250 - WARNING - django.request - Forbidden: /api/v1/backend/
2023-11-13 09:20:04,600 - WARNING - django.request - Forbidden: /api/v1/backend/
2023-11-13 09:20:07,321 - WARNING - django.request - Forbidden: /api/v1/backend/
2023-11-13 09:20:25,431 - WARNING - django.request - Forbidden: /api/v1/backend/
2023-11-13 09:20:51,370 - WARNING - django.request - Not Found: /api/v1/backend/communtiy
2023-11-13 09:20:57,136 - WARNING - django.request - Forbidden: /api/v1/backend/community
2023-11-13 09:21:33,531 - WARNING - django.request - Forbidden: /api/v1/backend/community
2023-11-13 09:23:14,392 - WARNING - django.request - Forbidden: /api/v1/backend/community
2023-11-13 09:23:43,602 - INFO - django.utils.autoreload - /home/olagold-hackxx/Projects/Portfolio/backend/climate_wavers/urls.py changed, reloading.
2023-11-13 09:23:52,068 - ERROR - django.request - Internal Server Error: /api/v1/backend
Traceback (most recent call last):
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/utils/deprecation.py", line 116, in __call__
    response = self.process_request(request)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/middleware/common.py", line 54, in process_request
    path = self.get_full_path_with_slash(request)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/middleware/common.py", line 88, in get_full_path_with_slash
    raise RuntimeError(
RuntimeError: You called this URL via POST, but the URL doesn't end in a slash and you have APPEND_SLASH set. Django can't redirect to the slash URL while maintaining POST data. Change your form to point to localhost:8001/api/v1/backend/ (note the trailing slash), or set APPEND_SLASH=False in your Django settings.
2023-11-13 09:24:08,750 - WARNING - django.request - Forbidden: /api/v1/backend/
2023-11-13 09:24:33,159 - INFO - django.utils.autoreload - /home/olagold-hackxx/Projects/Portfolio/backend/climate_wavers/urls.py changed, reloading.
2023-11-13 09:24:39,266 - WARNING - django.request - Forbidden: /api/v1/backend/
2023-11-13 09:30:16,325 - WARNING - django.request - Method Not Allowed: /api/v1/backend/
2023-11-13 09:30:41,691 - ERROR - climatewavers - Follower matching query does not exist.
2023-11-18 12:15:45,911 - ERROR - climatewavers - (1062, "Duplicate entry 'aileruenterprise@gmail.com' for key 'user.email'")
2023-11-18 12:15:45,913 - WARNING - django.request - Bad Request: /api/v1/backend/register
2023-11-18 12:57:13,990 - INFO - django.utils.autoreload - /home/olagold-hackxx/Projects/Portfolio/backend/climate_wavers/views.py changed, reloading.
2023-11-18 13:04:02,526 - INFO - django.utils.autoreload - /home/olagold-hackxx/Projects/Portfolio/backend/climate_wavers/views.py changed, reloading.
2023-11-18 13:05:47,020 - ERROR - climatewavers - 'User' object is not subscriptable
2023-11-18 13:05:47,025 - WARNING - django.request - Bad Request: /api/v1/backend/register
2023-11-18 13:06:13,092 - INFO - django.utils.autoreload - /home/olagold-hackxx/Projects/Portfolio/backend/climate_wavers/views.py changed, reloading.
2023-11-18 13:17:17,071 - ERROR - climatewavers - [Errno -3] Temporary failure in name resolution
2023-11-18 13:17:17,078 - WARNING - django.request - Bad Request: /api/v1/backend/register
2023-11-18 13:28:08,393 - INFO - django.utils.autoreload - /home/olagold-hackxx/Projects/Portfolio/backend/climate_wavers/views.py changed, reloading.
2023-11-18 13:28:54,019 - ERROR - climatewavers - [Errno -3] Temporary failure in name resolution
2023-11-18 13:28:54,022 - WARNING - django.request - Bad Request: /api/v1/backend/register
2023-11-18 13:32:11,382 - ERROR - climatewavers - [Errno -3] Temporary failure in name resolution
2023-11-18 13:32:11,386 - WARNING - django.request - Bad Request: /api/v1/backend/register
2023-11-18 13:36:26,309 - INFO - django.utils.autoreload - /home/olagold-hackxx/Projects/Portfolio/backend/climate_wavers/views.py changed, reloading.
2023-11-18 13:37:36,815 - INFO - django.utils.autoreload - /home/olagold-hackxx/Projects/Portfolio/backend/climate_wavers/views.py changed, reloading.
2023-11-18 13:41:05,249 - ERROR - climatewavers - (1062, "Duplicate entry 'aileruenterprise@gmail.com' for key 'user.email'")
2023-11-18 13:41:05,253 - WARNING - django.request - Bad Request: /api/v1/backend/register
2023-11-18 14:06:49,201 - ERROR - climatewavers - (1062, "Duplicate entry '46e82e5d-852d-4e26-a4bb-4a98956fac73' for key 'token.user_id'")
2023-11-18 16:16:12,901 - ERROR - climatewavers - Signature age 7780 > 3600 seconds
2023-11-18 16:16:13,162 - ERROR - climatewavers - Signature age 7781 > 3600 seconds
2023-11-18 16:41:48,262 - WARNING - django.request - Unauthorized: /api/v1/backend/undefined/profile
2023-11-18 16:41:54,291 - WARNING - django.request - Unauthorized: /api/v1/backend/undefined/profile
2023-11-18 16:56:35,907 - WARNING - django.request - Unauthorized: /api/v1/backend/undefined/profile
2023-11-18 16:56:41,087 - WARNING - django.request - Unauthorized: /api/v1/backend/undefined/profile
2023-11-18 17:02:52,351 - WARNING - django.request - Unauthorized: /api/v1/backend/undefined/profile
2023-11-18 17:02:55,623 - WARNING - django.request - Unauthorized: /api/v1/backend/undefined/profile
2023-11-18 17:12:35,743 - WARNING - django.request - Unauthorized: /api/v1/backend/undefined/profile
2023-11-18 17:13:02,652 - WARNING - django.request - Unauthorized: /api/v1/backend/undefined/profile
2023-11-18 17:14:05,183 - WARNING - django.request - Unauthorized: /api/v1/backend/undefined/profile
2023-11-18 17:17:01,912 - WARNING - django.request - Unauthorized: /api/v1/backend/undefined/profile
2023-11-18 17:17:18,811 - WARNING - django.request - Unauthorized: /api/v1/backend/undefined/profile
2023-11-18 17:18:38,973 - WARNING - django.request - Unauthorized: /api/v1/backend/undefined/profile
2023-11-18 17:20:58,227 - WARNING - django.request - Unauthorized: /api/v1/backend/undefined/profile
2023-11-18 17:21:46,364 - WARNING - django.request - Unauthorized: /api/v1/backend/undefined/profile
2023-11-18 17:22:33,202 - WARNING - django.request - Unauthorized: /api/v1/backend/undefined/profile
2023-11-18 17:22:46,511 - WARNING - django.request - Unauthorized: /api/v1/backend/undefined/profile
2023-11-18 17:23:41,220 - WARNING - django.request - Unauthorized: /api/v1/backend/undefined/profile
2023-11-18 17:23:50,497 - WARNING - django.request - Unauthorized: /api/v1/backend/undefined/profile
2023-11-18 17:26:44,404 - WARNING - django.request - Unauthorized: /api/v1/backend/undefined/profile
2023-11-18 17:27:00,759 - WARNING - django.request - Unauthorized: /api/v1/backend/undefined/profile
2023-11-18 17:27:17,698 - WARNING - django.request - Unauthorized: /api/v1/backend/undefined/profile
2023-11-18 17:28:29,831 - WARNING - django.request - Unauthorized: /api/v1/backend/undefined/profile
2023-11-18 17:28:34,270 - WARNING - django.request - Unauthorized: /api/v1/backend/undefined/profile
2023-11-18 17:28:37,475 - WARNING - django.request - Unauthorized: /api/v1/backend/undefined/profile
2023-11-18 17:29:33,825 - WARNING - django.request - Unauthorized: /api/v1/backend/undefined/profile
2023-11-18 17:30:04,851 - WARNING - django.request - Unauthorized: /api/v1/backend/undefined/profile
2023-11-18 17:33:20,408 - WARNING - django.request - Unauthorized: /api/v1/backend/undefined/profile
2023-11-18 17:34:05,571 - WARNING - django.request - Unauthorized: /api/v1/backend/undefined/profile
2023-11-18 17:37:33,231 - WARNING - django.request - Unauthorized: /api/v1/backend/undefined/profile
2023-11-18 17:37:35,815 - WARNING - django.request - Unauthorized: /api/v1/backend/undefined/profile
2023-11-18 17:37:40,224 - WARNING - django.request - Unauthorized: /api/v1/backend/undefined/profile
2023-11-18 17:39:49,853 - WARNING - django.request - Unauthorized: /api/v1/backend/undefined/profile
2023-11-18 17:40:11,370 - WARNING - django.request - Unauthorized: /api/v1/backend/undefined/profile
2023-11-18 17:42:25,716 - WARNING - django.request - Unauthorized: /api/v1/backend/undefined/profile
2023-11-18 17:43:04,237 - WARNING - django.request - Unauthorized: /api/v1/backend/undefined/profile
2023-11-18 17:44:43,194 - WARNING - django.request - Unauthorized: /api/v1/backend/undefined/profile
2023-11-18 17:45:03,217 - WARNING - django.request - Unauthorized: /api/v1/backend/undefined/profile
2023-11-18 17:45:23,902 - WARNING - django.request - Unauthorized: /api/v1/backend/undefined/profile
2023-11-18 17:45:29,901 - WARNING - django.request - Unauthorized: /api/v1/backend/undefined/profile
2023-11-18 17:46:56,441 - WARNING - django.request - Unauthorized: /api/v1/backend/undefined/profile
2023-11-18 17:47:01,743 - WARNING - django.request - Unauthorized: /api/v1/backend/undefined/profile
2023-11-18 17:47:25,729 - WARNING - django.request - Unauthorized: /api/v1/backend/undefined/profile
2023-11-18 17:47:58,379 - WARNING - django.request - Unauthorized: /api/v1/backend/undefined/profile
2023-11-18 17:49:45,519 - WARNING - django.request - Unauthorized: /api/v1/backend/undefined/profile
2023-11-18 17:49:52,070 - WARNING - django.request - Unauthorized: /api/v1/backend/undefined/profile
2023-11-18 17:50:56,905 - WARNING - django.request - Unauthorized: /api/v1/backend/undefined/profile
2023-11-18 17:52:50,829 - WARNING - django.request - Unauthorized: /api/v1/backend/undefined/profile
2023-11-18 17:56:45,284 - WARNING - django.request - Unauthorized: /api/v1/backend/undefined/profile
2023-11-18 17:56:49,116 - WARNING - django.request - Unauthorized: /api/v1/backend/undefined/profile
2023-11-18 17:59:08,178 - WARNING - django.request - Unauthorized: /api/v1/backend/undefined/profile
2023-11-18 18:00:45,651 - WARNING - django.request - Unauthorized: /api/v1/backend/undefined/profile
2023-11-18 18:01:44,954 - WARNING - django.request - Unauthorized: /api/v1/backend/undefined/profile
2023-11-18 18:02:12,759 - WARNING - django.request - Unauthorized: /api/v1/backend/undefined/profile
2023-11-18 18:08:19,073 - WARNING - django.request - Unauthorized: /api/v1/backend/undefined/profile
2023-11-18 21:39:31,982 - ERROR - climatewavers - Token is invalid or expired
2023-11-18 21:41:01,967 - ERROR - climatewavers - Token is invalid or expired
2023-11-18 21:45:28,743 - ERROR - climatewavers - (1062, "Duplicate entry 'aileruabdulqoyyumenterprise@gmail.com' for key 'user.email'")
2023-11-18 21:45:28,745 - WARNING - django.request - Bad Request: /api/v1/backend/register
2023-11-18 21:47:16,380 - ERROR - climatewavers - User matching query does not exist.
2023-11-18 21:47:16,381 - WARNING - django.request - Bad Request: /api/v1/backend/undefined/verify
2023-11-18 21:54:09,678 - ERROR - climatewavers - (1062, "Duplicate entry '93810901-e1ee-44b0-b17c-fb7665fee9ec' for key 'token.user_id'")
2023-11-18 22:34:19,312 - WARNING - django.request - Unauthorized: /api/v1/backend/abdul/profile
2023-11-18 22:34:49,808 - WARNING - django.request - Unauthorized: /api/v1/backend/abdul/profile
2023-11-18 23:32:49,626 - WARNING - django.request - Forbidden: /api/v1/backend/posts/create
2023-11-19 04:34:15,200 - WARNING - django.request - Unauthorized: /api/v1/backend/login
2023-11-19 04:35:38,932 - WARNING - django.request - Unauthorized: /api/v1/backend/login
2023-11-19 04:36:07,939 - WARNING - django.request - Unauthorized: /api/v1/backend/login
2023-11-19 04:56:34,549 - WARNING - django.request - Unsupported Media Type: /api/v1/backend/login
2023-11-19 04:57:52,823 - WARNING - django.request - Unsupported Media Type: /api/v1/backend/login
2023-11-19 04:58:08,227 - WARNING - django.request - Unsupported Media Type: /api/v1/backend/login
2023-11-19 04:58:39,307 - WARNING - django.request - Unsupported Media Type: /api/v1/backend/login
2023-11-19 04:59:20,738 - WARNING - django.request - Unsupported Media Type: /api/v1/backend/login
2023-11-19 05:14:58,222 - INFO - django.utils.autoreload - /home/olagold-hackxx/Projects/Portfolio/backend/climate_configure/settings.py changed, reloading.
2023-11-19 05:15:15,320 - WARNING - django.request - Unauthorized: /api/v1/backend/login
2023-11-19 05:17:39,312 - ERROR - climatewavers - Follower matching query does not exist.
2023-11-19 05:17:39,318 - WARNING - django.request - Unauthorized: /api/v1/backend/abdul/profile
2023-11-19 05:23:49,638 - ERROR - climatewavers - Follower matching query does not exist.
2023-11-19 05:23:49,640 - WARNING - django.request - Unauthorized: /api/v1/backend/abdul/profile
2023-11-19 05:24:27,503 - ERROR - climatewavers - Follower matching query does not exist.
2023-11-19 05:24:27,504 - WARNING - django.request - Unauthorized: /api/v1/backend/abdul/profile
2023-11-19 05:25:14,355 - INFO - django.utils.autoreload - /home/olagold-hackxx/Projects/Portfolio/backend/climate_wavers/views.py changed, reloading.
2023-11-19 05:25:21,205 - ERROR - climatewavers - Follower matching query does not exist.
2023-11-19 05:26:03,190 - INFO - django.utils.autoreload - /home/olagold-hackxx/Projects/Portfolio/backend/climate_wavers/views.py changed, reloading.
2023-11-19 05:28:54,826 - INFO - django.utils.autoreload - /home/olagold-hackxx/Projects/Portfolio/backend/climate_wavers/views.py changed, reloading.
2023-11-19 05:29:00,585 - ERROR - climatewavers - No Follower matches the given query.
2023-11-19 05:29:00,587 - WARNING - django.request - Unauthorized: /api/v1/backend/abdul/profile
2023-11-19 05:45:05,615 - ERROR - climatewavers - Follower matching query does not exist.
2023-11-19 05:47:54,911 - ERROR - climatewavers - Follower matching query does not exist.
2023-11-19 05:51:54,788 - ERROR - climatewavers - Follower matching query does not exist.
2023-11-19 06:30:54,136 - ERROR - climatewavers - Follower matching query does not exist.
2023-11-19 06:31:37,252 - ERROR - climatewavers - Follower matching query does not exist.
2023-11-19 06:31:43,879 - ERROR - climatewavers - Follower matching query does not exist.
2023-11-19 06:32:23,545 - ERROR - climatewavers - Follower matching query does not exist.
2023-11-19 06:32:37,046 - ERROR - climatewavers - Follower matching query does not exist.
2023-11-19 06:32:42,914 - ERROR - climatewavers - Follower matching query does not exist.
2023-11-19 06:34:13,649 - ERROR - climatewavers - Follower matching query does not exist.
2023-11-19 06:34:14,028 - ERROR - climatewavers - Follower matching query does not exist.
2023-11-19 06:34:16,100 - ERROR - climatewavers - Follower matching query does not exist.
2023-11-19 06:34:46,277 - ERROR - climatewavers - Follower matching query does not exist.
2023-11-19 06:34:47,077 - ERROR - climatewavers - Follower matching query does not exist.
2023-11-19 06:34:49,555 - ERROR - climatewavers - Follower matching query does not exist.
2023-11-19 06:34:58,512 - ERROR - climatewavers - Follower matching query does not exist.
2023-11-19 06:37:18,767 - ERROR - climatewavers - Follower matching query does not exist.
2023-11-19 06:37:25,625 - ERROR - climatewavers - Follower matching query does not exist.
2023-11-19 06:41:34,102 - ERROR - climatewavers - Follower matching query does not exist.
2023-11-19 06:45:10,368 - INFO - django.utils.autoreload - /home/olagold-hackxx/Projects/Portfolio/backend/climate_wavers/serializers.py changed, reloading.
2023-11-19 06:45:25,480 - ERROR - django.request - Internal Server Error: /api/v1/backend/
Traceback (most recent call last):
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "/home/olagold-hackxx/Projects/Portfolio/backend/climate_wavers/views.py", line 37, in index
    return JsonResponse({"all_posts": serializer.data, "access_token": request.access_token})
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/serializers.py", line 768, in data
    ret = super().data
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/serializers.py", line 253, in data
    self._data = self.to_representation(self.instance)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/serializers.py", line 686, in to_representation
    return [
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/serializers.py", line 687, in <listcomp>
    self.child.to_representation(item) for item in iterable
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/serializers.py", line 522, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/fields.py", line 1837, in to_representation
    method = getattr(self.parent, self.method_name)
AttributeError: 'PostSerializer' object has no attribute 'get_savers_count'
2023-11-19 06:45:25,487 - ERROR - django.request - Internal Server Error: /api/v1/backend/
Traceback (most recent call last):
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "/home/olagold-hackxx/Projects/Portfolio/backend/climate_wavers/views.py", line 37, in index
    return JsonResponse({"all_posts": serializer.data, "access_token": request.access_token})
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/serializers.py", line 768, in data
    ret = super().data
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/serializers.py", line 253, in data
    self._data = self.to_representation(self.instance)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/serializers.py", line 686, in to_representation
    return [
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/serializers.py", line 687, in <listcomp>
    self.child.to_representation(item) for item in iterable
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/serializers.py", line 522, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/fields.py", line 1837, in to_representation
    method = getattr(self.parent, self.method_name)
AttributeError: 'PostSerializer' object has no attribute 'get_savers_count'
2023-11-19 06:45:25,506 - ERROR - django.request - Internal Server Error: /api/v1/backend/
Traceback (most recent call last):
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "/home/olagold-hackxx/Projects/Portfolio/backend/climate_wavers/views.py", line 37, in index
    return JsonResponse({"all_posts": serializer.data, "access_token": request.access_token})
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/serializers.py", line 768, in data
    ret = super().data
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/serializers.py", line 253, in data
    self._data = self.to_representation(self.instance)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/serializers.py", line 686, in to_representation
    return [
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/serializers.py", line 687, in <listcomp>
    self.child.to_representation(item) for item in iterable
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/serializers.py", line 522, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/fields.py", line 1837, in to_representation
    method = getattr(self.parent, self.method_name)
AttributeError: 'PostSerializer' object has no attribute 'get_savers_count'
2023-11-19 06:45:25,514 - ERROR - django.request - Internal Server Error: /api/v1/backend/
Traceback (most recent call last):
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "/home/olagold-hackxx/Projects/Portfolio/backend/climate_wavers/views.py", line 37, in index
    return JsonResponse({"all_posts": serializer.data, "access_token": request.access_token})
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/serializers.py", line 768, in data
    ret = super().data
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/serializers.py", line 253, in data
    self._data = self.to_representation(self.instance)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/serializers.py", line 686, in to_representation
    return [
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/serializers.py", line 687, in <listcomp>
    self.child.to_representation(item) for item in iterable
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/serializers.py", line 522, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/fields.py", line 1837, in to_representation
    method = getattr(self.parent, self.method_name)
AttributeError: 'PostSerializer' object has no attribute 'get_savers_count'
2023-11-19 06:45:34,711 - ERROR - django.request - Internal Server Error: /api/v1/backend/
Traceback (most recent call last):
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "/home/olagold-hackxx/Projects/Portfolio/backend/climate_wavers/views.py", line 37, in index
    return JsonResponse({"all_posts": serializer.data, "access_token": request.access_token})
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/serializers.py", line 768, in data
    ret = super().data
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/serializers.py", line 253, in data
    self._data = self.to_representation(self.instance)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/serializers.py", line 686, in to_representation
    return [
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/serializers.py", line 687, in <listcomp>
    self.child.to_representation(item) for item in iterable
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/serializers.py", line 522, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/fields.py", line 1837, in to_representation
    method = getattr(self.parent, self.method_name)
AttributeError: 'PostSerializer' object has no attribute 'get_savers_count'
2023-11-19 06:45:34,788 - ERROR - django.request - Internal Server Error: /api/v1/backend/
Traceback (most recent call last):
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "/home/olagold-hackxx/Projects/Portfolio/backend/climate_wavers/views.py", line 37, in index
    return JsonResponse({"all_posts": serializer.data, "access_token": request.access_token})
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/serializers.py", line 768, in data
    ret = super().data
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/serializers.py", line 253, in data
    self._data = self.to_representation(self.instance)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/serializers.py", line 686, in to_representation
    return [
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/serializers.py", line 687, in <listcomp>
    self.child.to_representation(item) for item in iterable
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/serializers.py", line 522, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/fields.py", line 1837, in to_representation
    method = getattr(self.parent, self.method_name)
AttributeError: 'PostSerializer' object has no attribute 'get_savers_count'
2023-11-19 06:45:34,918 - ERROR - django.request - Internal Server Error: /api/v1/backend/
Traceback (most recent call last):
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "/home/olagold-hackxx/Projects/Portfolio/backend/climate_wavers/views.py", line 37, in index
    return JsonResponse({"all_posts": serializer.data, "access_token": request.access_token})
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/serializers.py", line 768, in data
    ret = super().data
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/serializers.py", line 253, in data
    self._data = self.to_representation(self.instance)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/serializers.py", line 686, in to_representation
    return [
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/serializers.py", line 687, in <listcomp>
    self.child.to_representation(item) for item in iterable
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/serializers.py", line 522, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/fields.py", line 1837, in to_representation
    method = getattr(self.parent, self.method_name)
AttributeError: 'PostSerializer' object has no attribute 'get_savers_count'
2023-11-19 06:45:34,924 - ERROR - django.request - Internal Server Error: /api/v1/backend/
Traceback (most recent call last):
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "/home/olagold-hackxx/Projects/Portfolio/backend/climate_wavers/views.py", line 37, in index
    return JsonResponse({"all_posts": serializer.data, "access_token": request.access_token})
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/serializers.py", line 768, in data
    ret = super().data
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/serializers.py", line 253, in data
    self._data = self.to_representation(self.instance)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/serializers.py", line 686, in to_representation
    return [
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/serializers.py", line 687, in <listcomp>
    self.child.to_representation(item) for item in iterable
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/serializers.py", line 522, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/fields.py", line 1837, in to_representation
    method = getattr(self.parent, self.method_name)
AttributeError: 'PostSerializer' object has no attribute 'get_savers_count'
2023-11-19 06:47:01,500 - INFO - django.utils.autoreload - /home/olagold-hackxx/Projects/Portfolio/backend/climate_wavers/models.py changed, reloading.
2023-11-19 06:47:33,625 - ERROR - django.request - Internal Server Error: /api/v1/backend/
Traceback (most recent call last):
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "/home/olagold-hackxx/Projects/Portfolio/backend/climate_wavers/views.py", line 37, in index
    return JsonResponse({"all_posts": serializer.data, "access_token": request.access_token})
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/serializers.py", line 768, in data
    ret = super().data
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/serializers.py", line 253, in data
    self._data = self.to_representation(self.instance)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/serializers.py", line 686, in to_representation
    return [
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/serializers.py", line 687, in <listcomp>
    self.child.to_representation(item) for item in iterable
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/serializers.py", line 522, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/fields.py", line 1837, in to_representation
    method = getattr(self.parent, self.method_name)
AttributeError: 'PostSerializer' object has no attribute 'get_savers_count'
2023-11-19 06:47:33,627 - ERROR - django.request - Internal Server Error: /api/v1/backend/
Traceback (most recent call last):
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "/home/olagold-hackxx/Projects/Portfolio/backend/climate_wavers/views.py", line 37, in index
    return JsonResponse({"all_posts": serializer.data, "access_token": request.access_token})
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/serializers.py", line 768, in data
    ret = super().data
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/serializers.py", line 253, in data
    self._data = self.to_representation(self.instance)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/serializers.py", line 686, in to_representation
    return [
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/serializers.py", line 687, in <listcomp>
    self.child.to_representation(item) for item in iterable
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/serializers.py", line 522, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/fields.py", line 1837, in to_representation
    method = getattr(self.parent, self.method_name)
AttributeError: 'PostSerializer' object has no attribute 'get_savers_count'
2023-11-19 06:47:33,668 - ERROR - django.request - Internal Server Error: /api/v1/backend/
Traceback (most recent call last):
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "/home/olagold-hackxx/Projects/Portfolio/backend/climate_wavers/views.py", line 37, in index
    return JsonResponse({"all_posts": serializer.data, "access_token": request.access_token})
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/serializers.py", line 768, in data
    ret = super().data
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/serializers.py", line 253, in data
    self._data = self.to_representation(self.instance)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/serializers.py", line 686, in to_representation
    return [
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/serializers.py", line 687, in <listcomp>
    self.child.to_representation(item) for item in iterable
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/serializers.py", line 522, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/fields.py", line 1837, in to_representation
    method = getattr(self.parent, self.method_name)
AttributeError: 'PostSerializer' object has no attribute 'get_savers_count'
2023-11-19 06:47:33,675 - ERROR - django.request - Internal Server Error: /api/v1/backend/
Traceback (most recent call last):
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "/home/olagold-hackxx/Projects/Portfolio/backend/climate_wavers/views.py", line 37, in index
    return JsonResponse({"all_posts": serializer.data, "access_token": request.access_token})
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/serializers.py", line 768, in data
    ret = super().data
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/serializers.py", line 253, in data
    self._data = self.to_representation(self.instance)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/serializers.py", line 686, in to_representation
    return [
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/serializers.py", line 687, in <listcomp>
    self.child.to_representation(item) for item in iterable
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/serializers.py", line 522, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/fields.py", line 1837, in to_representation
    method = getattr(self.parent, self.method_name)
AttributeError: 'PostSerializer' object has no attribute 'get_savers_count'
2023-11-19 06:48:01,952 - INFO - django.utils.autoreload - /home/olagold-hackxx/Projects/Portfolio/backend/climate_wavers/models.py changed, reloading.
2023-11-19 06:48:10,447 - INFO - django.utils.autoreload - /home/olagold-hackxx/Projects/Portfolio/backend/climate_wavers/serializers.py changed, reloading.
2023-11-19 06:48:29,156 - ERROR - climatewavers - Follower matching query does not exist.
2023-11-19 07:04:01,287 - INFO - django.utils.autoreload - /home/olagold-hackxx/Projects/Portfolio/backend/climate_wavers/views.py changed, reloading.
2023-11-19 07:18:33,207 - ERROR - climatewavers - Follower matching query does not exist.
2023-11-19 07:23:23,691 - INFO - django.utils.autoreload - /home/olagold-hackxx/Projects/Portfolio/backend/climate_wavers/middlewares.py changed, reloading.
2023-11-19 07:25:05,355 - INFO - django.utils.autoreload - /home/olagold-hackxx/Projects/Portfolio/backend/climate_wavers/middlewares.py changed, reloading.
2023-11-19 07:25:11,701 - ERROR - climatewavers - Follower matching query does not exist.
2023-11-19 07:25:12,129 - WARNING - django.request - Not Found: /media/posts/trust4.jpeg
2023-11-19 07:25:13,524 - WARNING - django.request - Not Found: /media/posts/trust4.jpeg
2023-11-19 07:27:54,094 - WARNING - django.request - Not Found: /media/posts/trust4.jpeg
2023-11-19 07:35:03,934 - INFO - django.utils.autoreload - /home/olagold-hackxx/Projects/Portfolio/backend/climate_configure/urls.py changed, reloading.
2023-11-19 07:37:27,052 - INFO - django.utils.autoreload - /home/olagold-hackxx/Projects/Portfolio/backend/climate_configure/urls.py changed, reloading.
2023-11-19 07:40:53,233 - INFO - django.utils.autoreload - /home/olagold-hackxx/Projects/Portfolio/backend/climate_wavers/urls.py changed, reloading.
2023-11-19 07:41:05,478 - WARNING - django.request - Not Found: /media/posts/trust4.jpeg
2023-11-19 07:41:05,556 - WARNING - django.request - Not Found: /media/posts/trust4.jpeg
2023-11-19 07:41:49,519 - INFO - django.utils.autoreload - /home/olagold-hackxx/Projects/Portfolio/backend/climate_configure/settings.py changed, reloading.
2023-11-19 07:42:08,998 - INFO - django.utils.autoreload - /home/olagold-hackxx/Projects/Portfolio/backend/climate_configure/settings.py changed, reloading.
2023-11-19 07:42:43,811 - INFO - django.utils.autoreload - /home/olagold-hackxx/Projects/Portfolio/backend/climate_configure/settings.py changed, reloading.
2023-11-19 07:42:50,852 - ERROR - climatewavers - Follower matching query does not exist.
2023-11-19 07:42:51,825 - WARNING - django.request - Not Found: /media/posts/trust4.jpeg
2023-11-19 07:43:11,382 - INFO - django.utils.autoreload - /home/olagold-hackxx/Projects/Portfolio/backend/climate_configure/settings.py changed, reloading.
2023-11-19 07:43:17,282 - ERROR - climatewavers - Follower matching query does not exist.
2023-11-19 07:43:18,983 - WARNING - django.request - Not Found: /media/posts/trust4.jpeg
2023-11-19 07:43:18,998 - WARNING - django.request - Not Found: /media/posts/trust4.jpeg
2023-11-19 07:43:44,394 - WARNING - django.request - Not Found: /media/posts/trust4.jpeg
2023-11-19 07:47:20,121 - WARNING - django.request - Not Found: /media/posts/trust4.jpeg
2023-11-19 07:48:58,959 - INFO - django.utils.autoreload - /home/olagold-hackxx/Projects/Portfolio/backend/climate_configure/settings.py changed, reloading.
2023-11-19 07:49:38,735 - ERROR - climatewavers - Follower matching query does not exist.
2023-11-19 07:49:39,845 - WARNING - django.request - Not Found: /media/posts/trust4.jpeg
2023-11-19 07:49:39,899 - WARNING - django.request - Not Found: /media/posts/trust4.jpeg
2023-11-19 07:50:45,682 - INFO - django.utils.autoreload - /home/olagold-hackxx/Projects/Portfolio/backend/climate_configure/settings.py changed, reloading.
2023-11-19 07:51:07,460 - WARNING - django.request - Not Found: /media/posts/trust4.jpeg
2023-11-19 07:59:49,080 - ERROR - climatewavers - Follower matching query does not exist.
2023-11-19 08:02:30,038 - ERROR - climatewavers - Follower matching query does not exist.
2023-11-19 08:03:14,275 - ERROR - climatewavers - Follower matching query does not exist.
2023-11-19 08:03:14,360 - ERROR - climatewavers - Follower matching query does not exist.
2023-11-19 08:03:59,514 - ERROR - climatewavers - Follower matching query does not exist.
2023-11-19 08:03:59,655 - ERROR - climatewavers - Follower matching query does not exist.
2023-11-19 08:14:05,658 - ERROR - climatewavers - Follower matching query does not exist.
2023-11-19 08:14:05,693 - ERROR - climatewavers - Follower matching query does not exist.
2023-11-19 08:14:05,707 - ERROR - climatewavers - Follower matching query does not exist.
2023-11-19 08:14:05,801 - ERROR - climatewavers - Follower matching query does not exist.
2023-11-19 08:14:05,955 - ERROR - climatewavers - Follower matching query does not exist.
2023-11-19 08:14:06,046 - ERROR - climatewavers - Follower matching query does not exist.
2023-11-19 08:14:06,431 - ERROR - climatewavers - Follower matching query does not exist.
2023-11-19 08:14:06,883 - ERROR - climatewavers - Follower matching query does not exist.
2023-11-19 08:14:07,498 - ERROR - climatewavers - Follower matching query does not exist.
2023-11-19 08:14:07,909 - ERROR - climatewavers - Follower matching query does not exist.
2023-11-19 08:16:34,278 - ERROR - climatewavers - Follower matching query does not exist.
2023-11-19 08:16:34,378 - ERROR - climatewavers - Follower matching query does not exist.
2023-11-19 08:16:34,524 - ERROR - climatewavers - Follower matching query does not exist.
2023-11-19 08:16:34,853 - ERROR - climatewavers - Follower matching query does not exist.
2023-11-19 08:16:34,944 - ERROR - climatewavers - Follower matching query does not exist.
2023-11-19 08:16:35,428 - ERROR - climatewavers - Follower matching query does not exist.
2023-11-19 08:16:36,385 - ERROR - climatewavers - Follower matching query does not exist.
2023-11-19 08:16:37,166 - ERROR - climatewavers - Follower matching query does not exist.
2023-11-19 08:17:07,717 - ERROR - climatewavers - Follower matching query does not exist.
2023-11-19 08:17:07,734 - ERROR - climatewavers - Follower matching query does not exist.
2023-11-19 08:17:07,830 - ERROR - climatewavers - Follower matching query does not exist.
2023-11-19 08:17:07,870 - ERROR - climatewavers - Follower matching query does not exist.
2023-11-19 08:17:07,926 - ERROR - climatewavers - Follower matching query does not exist.
2023-11-19 08:17:08,635 - ERROR - climatewavers - Follower matching query does not exist.
2023-11-19 08:17:09,251 - ERROR - climatewavers - Follower matching query does not exist.
2023-11-19 08:17:10,165 - ERROR - climatewavers - Follower matching query does not exist.
2023-11-19 08:17:33,724 - ERROR - climatewavers - Follower matching query does not exist.
2023-11-19 08:17:34,044 - ERROR - climatewavers - Follower matching query does not exist.
2023-11-19 08:17:34,588 - ERROR - climatewavers - Follower matching query does not exist.
2023-11-19 08:17:34,701 - ERROR - climatewavers - Follower matching query does not exist.
2023-11-19 08:32:45,215 - ERROR - climatewavers - Follower matching query does not exist.
2023-11-19 08:32:45,282 - ERROR - climatewavers - Follower matching query does not exist.
2023-11-19 08:32:45,535 - ERROR - climatewavers - Follower matching query does not exist.
2023-11-19 08:32:45,567 - ERROR - climatewavers - Follower matching query does not exist.
2023-11-19 08:35:12,158 - ERROR - climatewavers - Follower matching query does not exist.
2023-11-19 08:35:12,386 - ERROR - climatewavers - Follower matching query does not exist.
2023-11-19 08:35:12,552 - ERROR - climatewavers - Follower matching query does not exist.
2023-11-19 08:35:13,017 - ERROR - climatewavers - Follower matching query does not exist.
2023-11-19 08:35:18,267 - ERROR - climatewavers - Follower matching query does not exist.
2023-11-19 08:35:18,495 - ERROR - climatewavers - Follower matching query does not exist.
2023-11-19 08:38:38,994 - ERROR - climatewavers - Follower matching query does not exist.
2023-11-19 08:38:39,236 - ERROR - climatewavers - Follower matching query does not exist.
2023-11-19 08:38:39,416 - ERROR - climatewavers - Follower matching query does not exist.
2023-11-19 08:38:40,652 - ERROR - climatewavers - Follower matching query does not exist.
2023-11-19 08:38:41,281 - ERROR - climatewavers - Follower matching query does not exist.
2023-11-19 08:38:41,722 - ERROR - climatewavers - Follower matching query does not exist.
2023-11-19 08:40:59,729 - ERROR - climatewavers - Follower matching query does not exist.
2023-11-19 08:43:22,122 - INFO - django.utils.autoreload - /home/olagold-hackxx/Projects/Portfolio/backend/climate_wavers/serializers.py changed, reloading.
2023-11-19 08:47:54,746 - ERROR - climatewavers - Follower matching query does not exist.
2023-11-19 08:48:15,354 - ERROR - climatewavers - Follower matching query does not exist.
2023-11-19 08:50:48,376 - ERROR - climatewavers - Follower matching query does not exist.
2023-11-19 08:50:56,799 - ERROR - climatewavers - Follower matching query does not exist.
2023-11-19 08:51:59,179 - ERROR - climatewavers - Follower matching query does not exist.
2023-11-19 09:48:15,037 - WARNING - django.request - Not Found: /api/v1/backend/comments/581d1274-4044-468c-bb37-d9db71ec4c78/comment
2023-11-19 09:48:15,056 - WARNING - django.request - Not Found: /api/v1/backend/comments/581d1274-4044-468c-bb37-d9db71ec4c78/comment
2023-11-19 09:53:26,064 - WARNING - django.request - Not Found: /api/v1/backend/comments/581d1274-4044-468c-bb37-d9db71ec4c78/comment
2023-11-19 09:54:00,655 - WARNING - django.request - Not Found: /api/v1/backend/comments/581d1274-4044-468c-bb37-d9db71ec4c78/comment
2023-11-19 09:54:15,196 - WARNING - django.request - Not Found: /api/v1/backend/comments/581d1274-4044-468c-bb37-d9db71ec4c78/comment
2023-11-19 09:54:51,232 - WARNING - django.request - Not Found: /api/v1/backend/comments/581d1274-4044-468c-bb37-d9db71ec4c78/comment
2023-11-19 09:56:56,889 - WARNING - django.request - Not Found: /api/v1/backend/comments/581d1274-4044-468c-bb37-d9db71ec4c78/comment
2023-11-19 09:56:56,899 - WARNING - django.request - Not Found: /api/v1/backend/comments/581d1274-4044-468c-bb37-d9db71ec4c78/comment
2023-11-19 10:07:57,600 - WARNING - django.request - Not Found: /api/v1/backend/comments/6690a49a-bfc6-46ea-8560-be0a4516c380/comment
2023-11-19 10:07:57,639 - WARNING - django.request - Not Found: /api/v1/backend/comments/6690a49a-bfc6-46ea-8560-be0a4516c380/comment
2023-11-19 10:09:03,118 - WARNING - django.request - Not Found: /api/v1/backend/comments/6690a49a-bfc6-46ea-8560-be0a4516c380/comment
2023-11-19 10:09:10,917 - WARNING - django.request - Not Found: /api/v1/backend/comments/6690a49a-bfc6-46ea-8560-be0a4516c380/comment
2023-11-19 10:09:10,927 - WARNING - django.request - Not Found: /api/v1/backend/comments/6690a49a-bfc6-46ea-8560-be0a4516c380/comment
2023-11-19 10:09:20,448 - WARNING - django.request - Not Found: /api/v1/backend/comments/426cf682-54a4-4d78-953f-f3b9d9eebcac/comment
2023-11-19 10:09:20,471 - WARNING - django.request - Not Found: /api/v1/backend/comments/426cf682-54a4-4d78-953f-f3b9d9eebcac/comment
2023-11-19 10:09:39,422 - WARNING - django.request - Not Found: /api/v1/backend/comments/581d1274-4044-468c-bb37-d9db71ec4c78/comment
2023-11-19 10:09:39,446 - WARNING - django.request - Not Found: /api/v1/backend/comments/581d1274-4044-468c-bb37-d9db71ec4c78/comment
2023-11-19 10:10:19,804 - WARNING - django.request - Not Found: /api/v1/backend/comments/6690a49a-bfc6-46ea-8560-be0a4516c380/comment
2023-11-19 10:10:19,832 - WARNING - django.request - Not Found: /api/v1/backend/comments/6690a49a-bfc6-46ea-8560-be0a4516c380/comment
2023-11-19 10:11:53,593 - WARNING - django.request - Not Found: /api/v1/backend/comments/6690a49a-bfc6-46ea-8560-be0a4516c380/comment
2023-11-19 10:12:21,240 - ERROR - django.request - Internal Server Error: /api/v1/backend/posts/6690a49a-bfc6-46ea-8560-be0a4516c380/comment
Traceback (most recent call last):
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "/home/olagold-hackxx/Projects/Portfolio/backend/climate_wavers/views.py", line 675, in comment
    subcomment_count = comments.subcomments.count()
AttributeError: 'QuerySet' object has no attribute 'subcomments'
2023-11-19 10:12:45,157 - ERROR - django.request - Internal Server Error: /api/v1/backend/posts/6690a49a-bfc6-46ea-8560-be0a4516c380/comment
Traceback (most recent call last):
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "/home/olagold-hackxx/Projects/Portfolio/backend/climate_wavers/views.py", line 675, in comment
    subcomment_count = comments.subcomments.count()
AttributeError: 'QuerySet' object has no attribute 'subcomments'
2023-11-19 10:14:16,663 - ERROR - django.request - Internal Server Error: /api/v1/backend/posts/6690a49a-bfc6-46ea-8560-be0a4516c380/comment
Traceback (most recent call last):
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "/home/olagold-hackxx/Projects/Portfolio/backend/climate_wavers/views.py", line 675, in comment
    subcomment_count = comments.subcomments.count()
AttributeError: 'QuerySet' object has no attribute 'subcomments'
2023-11-19 10:16:50,600 - ERROR - django.request - Internal Server Error: /api/v1/backend/posts/6690a49a-bfc6-46ea-8560-be0a4516c380/comment
Traceback (most recent call last):
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "/home/olagold-hackxx/Projects/Portfolio/backend/climate_wavers/views.py", line 675, in comment
    subcomment_count = comments.subcomments.count()
AttributeError: 'QuerySet' object has no attribute 'subcomments'
2023-11-19 10:17:08,244 - ERROR - django.request - Internal Server Error: /api/v1/backend/posts/6690a49a-bfc6-46ea-8560-be0a4516c380/comment
Traceback (most recent call last):
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "/home/olagold-hackxx/Projects/Portfolio/backend/climate_wavers/views.py", line 675, in comment
    subcomment_count = comments.subcomments.count()
AttributeError: 'QuerySet' object has no attribute 'subcomments'
2023-11-19 10:17:08,249 - ERROR - django.request - Internal Server Error: /api/v1/backend/posts/6690a49a-bfc6-46ea-8560-be0a4516c380/comment
Traceback (most recent call last):
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "/home/olagold-hackxx/Projects/Portfolio/backend/climate_wavers/views.py", line 675, in comment
    subcomment_count = comments.subcomments.count()
AttributeError: 'QuerySet' object has no attribute 'subcomments'
2023-11-19 10:18:18,237 - ERROR - django.request - Internal Server Error: /api/v1/backend/posts/6690a49a-bfc6-46ea-8560-be0a4516c380/comment
Traceback (most recent call last):
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "/home/olagold-hackxx/Projects/Portfolio/backend/climate_wavers/views.py", line 675, in comment
    subcomment_count = comments.subcomments.count()
AttributeError: 'QuerySet' object has no attribute 'subcomments'
2023-11-19 10:18:18,238 - ERROR - django.request - Internal Server Error: /api/v1/backend/posts/6690a49a-bfc6-46ea-8560-be0a4516c380/comment
Traceback (most recent call last):
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "/home/olagold-hackxx/Projects/Portfolio/backend/climate_wavers/views.py", line 675, in comment
    subcomment_count = comments.subcomments.count()
AttributeError: 'QuerySet' object has no attribute 'subcomments'
2023-11-19 10:18:41,123 - ERROR - django.request - Internal Server Error: /api/v1/backend/posts/6690a49a-bfc6-46ea-8560-be0a4516c380/comment
Traceback (most recent call last):
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "/home/olagold-hackxx/Projects/Portfolio/backend/climate_wavers/views.py", line 675, in comment
    subcomment_count = comments.subcomments.count()
AttributeError: 'QuerySet' object has no attribute 'subcomments'
2023-11-19 10:19:55,742 - ERROR - django.request - Internal Server Error: /api/v1/backend/posts/6690a49a-bfc6-46ea-8560-be0a4516c380/comment
Traceback (most recent call last):
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "/home/olagold-hackxx/Projects/Portfolio/backend/climate_wavers/views.py", line 675, in comment
    subcomment_count = comments.subcomments.count()
AttributeError: 'QuerySet' object has no attribute 'subcomments'
2023-11-19 10:21:56,359 - ERROR - django.request - Internal Server Error: /api/v1/backend/posts/6690a49a-bfc6-46ea-8560-be0a4516c380/comment
Traceback (most recent call last):
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "/home/olagold-hackxx/Projects/Portfolio/backend/climate_wavers/views.py", line 675, in comment
    subcomment_count = comments.subcomments.count()
AttributeError: 'QuerySet' object has no attribute 'subcomments'
2023-11-19 10:21:56,375 - ERROR - django.request - Internal Server Error: /api/v1/backend/posts/6690a49a-bfc6-46ea-8560-be0a4516c380/comment
Traceback (most recent call last):
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "/home/olagold-hackxx/Projects/Portfolio/backend/climate_wavers/views.py", line 675, in comment
    subcomment_count = comments.subcomments.count()
AttributeError: 'QuerySet' object has no attribute 'subcomments'
2023-11-19 10:21:59,196 - ERROR - django.request - Internal Server Error: /api/v1/backend/posts/6690a49a-bfc6-46ea-8560-be0a4516c380/comment
Traceback (most recent call last):
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "/home/olagold-hackxx/Projects/Portfolio/backend/climate_wavers/views.py", line 675, in comment
    subcomment_count = comments.subcomments.count()
AttributeError: 'QuerySet' object has no attribute 'subcomments'
2023-11-19 10:21:59,268 - ERROR - django.request - Internal Server Error: /api/v1/backend/posts/6690a49a-bfc6-46ea-8560-be0a4516c380/comment
Traceback (most recent call last):
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "/home/olagold-hackxx/Projects/Portfolio/backend/climate_wavers/views.py", line 675, in comment
    subcomment_count = comments.subcomments.count()
AttributeError: 'QuerySet' object has no attribute 'subcomments'
2023-11-19 10:22:51,086 - INFO - django.utils.autoreload - /home/olagold-hackxx/Projects/Portfolio/backend/climate_wavers/views.py changed, reloading.
2023-11-19 10:26:32,033 - INFO - django.utils.autoreload - /home/olagold-hackxx/Projects/Portfolio/backend/climate_wavers/views.py changed, reloading.
2023-11-19 10:26:39,975 - ERROR - django.request - Internal Server Error: /api/v1/backend/posts/6690a49a-bfc6-46ea-8560-be0a4516c380/comment
Traceback (most recent call last):
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "/home/olagold-hackxx/Projects/Portfolio/backend/climate_wavers/views.py", line 675, in comment
    subcomment_count =  Comment.objects.filter(parent_comment=None).prefetch_related('subcomments').order_by('-created_at')
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/db/models/query.py", line 1149, in order_by
    obj.query.add_ordering(*field_names)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1993, in add_ordering
    self.names_to_path(item.split(LOOKUP_SEP), self.model._meta)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1539, in names_to_path
    raise FieldError("Cannot resolve keyword '%s' into field. "
django.core.exceptions.FieldError: Cannot resolve keyword 'created_at' into field. Choices are: comment_content, comment_time, commenter, commenter_id, content_image, id, parent_comment, parent_comment_id, post, post_id, subcomments
2023-11-19 10:26:39,992 - ERROR - django.request - Internal Server Error: /api/v1/backend/posts/6690a49a-bfc6-46ea-8560-be0a4516c380/comment
Traceback (most recent call last):
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "/home/olagold-hackxx/Projects/Portfolio/backend/climate_wavers/views.py", line 675, in comment
    subcomment_count =  Comment.objects.filter(parent_comment=None).prefetch_related('subcomments').order_by('-created_at')
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/db/models/query.py", line 1149, in order_by
    obj.query.add_ordering(*field_names)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1993, in add_ordering
    self.names_to_path(item.split(LOOKUP_SEP), self.model._meta)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1539, in names_to_path
    raise FieldError("Cannot resolve keyword '%s' into field. "
django.core.exceptions.FieldError: Cannot resolve keyword 'created_at' into field. Choices are: comment_content, comment_time, commenter, commenter_id, content_image, id, parent_comment, parent_comment_id, post, post_id, subcomments
2023-11-19 10:27:54,111 - INFO - django.utils.autoreload - /home/olagold-hackxx/Projects/Portfolio/backend/climate_wavers/views.py changed, reloading.
2023-11-19 10:28:03,715 - ERROR - django.request - Internal Server Error: /api/v1/backend/posts/6690a49a-bfc6-46ea-8560-be0a4516c380/comment
Traceback (most recent call last):
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "/home/olagold-hackxx/Projects/Portfolio/backend/climate_wavers/views.py", line 680, in comment
    return JsonResponse({"comments": serializer.data, "count": subcomment_count, "access_token": request.access_token}, status=200)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/http/response.py", line 603, in __init__
    data = json.dumps(data, cls=encoder, **json_dumps_params)
  File "/usr/lib/python3.10/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/usr/lib/python3.10/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.10/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/core/serializers/json.py", line 105, in default
    return super().default(o)
  File "/usr/lib/python3.10/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type QuerySet is not JSON serializable
2023-11-19 10:28:03,732 - ERROR - django.request - Internal Server Error: /api/v1/backend/posts/6690a49a-bfc6-46ea-8560-be0a4516c380/comment
Traceback (most recent call last):
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "/home/olagold-hackxx/Projects/Portfolio/backend/climate_wavers/views.py", line 680, in comment
    return JsonResponse({"comments": serializer.data, "count": subcomment_count, "access_token": request.access_token}, status=200)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/http/response.py", line 603, in __init__
    data = json.dumps(data, cls=encoder, **json_dumps_params)
  File "/usr/lib/python3.10/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/usr/lib/python3.10/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.10/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/core/serializers/json.py", line 105, in default
    return super().default(o)
  File "/usr/lib/python3.10/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type QuerySet is not JSON serializable
2023-11-19 10:28:53,334 - INFO - django.utils.autoreload - /home/olagold-hackxx/Projects/Portfolio/backend/climate_wavers/views.py changed, reloading.
2023-11-19 10:29:03,193 - ERROR - django.request - Internal Server Error: /api/v1/backend/posts/6690a49a-bfc6-46ea-8560-be0a4516c380/comment
Traceback (most recent call last):
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "/home/olagold-hackxx/Projects/Portfolio/backend/climate_wavers/views.py", line 681, in comment
    return JsonResponse({"comments": serializer.data, "count": subcomment_count, "access_token": request.access_token}, status=200)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/http/response.py", line 603, in __init__
    data = json.dumps(data, cls=encoder, **json_dumps_params)
  File "/usr/lib/python3.10/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/usr/lib/python3.10/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.10/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/core/serializers/json.py", line 105, in default
    return super().default(o)
  File "/usr/lib/python3.10/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type QuerySet is not JSON serializable
2023-11-19 10:29:03,196 - ERROR - django.request - Internal Server Error: /api/v1/backend/posts/6690a49a-bfc6-46ea-8560-be0a4516c380/comment
Traceback (most recent call last):
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "/home/olagold-hackxx/Projects/Portfolio/backend/climate_wavers/views.py", line 681, in comment
    return JsonResponse({"comments": serializer.data, "count": subcomment_count, "access_token": request.access_token}, status=200)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/http/response.py", line 603, in __init__
    data = json.dumps(data, cls=encoder, **json_dumps_params)
  File "/usr/lib/python3.10/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/usr/lib/python3.10/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.10/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/core/serializers/json.py", line 105, in default
    return super().default(o)
  File "/usr/lib/python3.10/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type QuerySet is not JSON serializable
2023-11-19 10:29:41,946 - INFO - django.utils.autoreload - /home/olagold-hackxx/Projects/Portfolio/backend/climate_wavers/views.py changed, reloading.
2023-11-19 10:29:52,958 - ERROR - django.request - Internal Server Error: /api/v1/backend/posts/6690a49a-bfc6-46ea-8560-be0a4516c380/comment
Traceback (most recent call last):
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "/home/olagold-hackxx/Projects/Portfolio/backend/climate_wavers/views.py", line 681, in comment
    return JsonResponse({"comments": serializer.data, "count": subcomment_count, "access_token": request.access_token}, status=200)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/http/response.py", line 603, in __init__
    data = json.dumps(data, cls=encoder, **json_dumps_params)
  File "/usr/lib/python3.10/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/usr/lib/python3.10/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.10/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/core/serializers/json.py", line 105, in default
    return super().default(o)
  File "/usr/lib/python3.10/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type ListSerializer is not JSON serializable
2023-11-19 10:29:52,968 - ERROR - django.request - Internal Server Error: /api/v1/backend/posts/6690a49a-bfc6-46ea-8560-be0a4516c380/comment
Traceback (most recent call last):
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "/home/olagold-hackxx/Projects/Portfolio/backend/climate_wavers/views.py", line 681, in comment
    return JsonResponse({"comments": serializer.data, "count": subcomment_count, "access_token": request.access_token}, status=200)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/http/response.py", line 603, in __init__
    data = json.dumps(data, cls=encoder, **json_dumps_params)
  File "/usr/lib/python3.10/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/usr/lib/python3.10/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.10/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/core/serializers/json.py", line 105, in default
    return super().default(o)
  File "/usr/lib/python3.10/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type ListSerializer is not JSON serializable
2023-11-19 10:30:45,936 - INFO - django.utils.autoreload - /home/olagold-hackxx/Projects/Portfolio/backend/climate_wavers/views.py changed, reloading.
2023-11-19 10:30:57,237 - ERROR - django.request - Internal Server Error: /api/v1/backend/posts/6690a49a-bfc6-46ea-8560-be0a4516c380/comment
Traceback (most recent call last):
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "/home/olagold-hackxx/Projects/Portfolio/backend/climate_wavers/views.py", line 682, in comment
    return JsonResponse({"comments": serializer.data, "count": subcomment_count, "access_token": request.access_token}, status=200)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/http/response.py", line 603, in __init__
    data = json.dumps(data, cls=encoder, **json_dumps_params)
  File "/usr/lib/python3.10/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/usr/lib/python3.10/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.10/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/core/serializers/json.py", line 105, in default
    return super().default(o)
  File "/usr/lib/python3.10/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type ListSerializer is not JSON serializable
2023-11-19 10:30:57,243 - ERROR - django.request - Internal Server Error: /api/v1/backend/posts/6690a49a-bfc6-46ea-8560-be0a4516c380/comment
Traceback (most recent call last):
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "/home/olagold-hackxx/Projects/Portfolio/backend/climate_wavers/views.py", line 682, in comment
    return JsonResponse({"comments": serializer.data, "count": subcomment_count, "access_token": request.access_token}, status=200)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/http/response.py", line 603, in __init__
    data = json.dumps(data, cls=encoder, **json_dumps_params)
  File "/usr/lib/python3.10/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/usr/lib/python3.10/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.10/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/core/serializers/json.py", line 105, in default
    return super().default(o)
  File "/usr/lib/python3.10/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type ListSerializer is not JSON serializable
2023-11-19 10:31:28,767 - INFO - django.utils.autoreload - /home/olagold-hackxx/Projects/Portfolio/backend/climate_wavers/views.py changed, reloading.
2023-11-19 10:31:38,047 - ERROR - django.request - Internal Server Error: /api/v1/backend/posts/6690a49a-bfc6-46ea-8560-be0a4516c380/comment
Traceback (most recent call last):
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "/home/olagold-hackxx/Projects/Portfolio/backend/climate_wavers/views.py", line 683, in comment
    return JsonResponse({"comments": serializer.data, "count": subcomment_count, "access_token": request.access_token}, status=200)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/http/response.py", line 603, in __init__
    data = json.dumps(data, cls=encoder, **json_dumps_params)
  File "/usr/lib/python3.10/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/usr/lib/python3.10/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.10/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/core/serializers/json.py", line 105, in default
    return super().default(o)
  File "/usr/lib/python3.10/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type ListSerializer is not JSON serializable
2023-11-19 10:31:38,051 - ERROR - django.request - Internal Server Error: /api/v1/backend/posts/6690a49a-bfc6-46ea-8560-be0a4516c380/comment
Traceback (most recent call last):
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "/home/olagold-hackxx/Projects/Portfolio/backend/climate_wavers/views.py", line 683, in comment
    return JsonResponse({"comments": serializer.data, "count": subcomment_count, "access_token": request.access_token}, status=200)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/http/response.py", line 603, in __init__
    data = json.dumps(data, cls=encoder, **json_dumps_params)
  File "/usr/lib/python3.10/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/usr/lib/python3.10/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.10/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/core/serializers/json.py", line 105, in default
    return super().default(o)
  File "/usr/lib/python3.10/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type ListSerializer is not JSON serializable
2023-11-19 10:38:33,019 - INFO - django.utils.autoreload - /home/olagold-hackxx/Projects/Portfolio/backend/climate_wavers/views.py changed, reloading.
2023-11-19 10:46:02,576 - INFO - django.utils.autoreload - /home/olagold-hackxx/Projects/Portfolio/backend/climate_wavers/serializers.py changed, reloading.
2023-11-19 10:47:10,098 - INFO - django.utils.autoreload - /home/olagold-hackxx/Projects/Portfolio/backend/climate_wavers/serializers.py changed, reloading.
2023-11-19 10:49:03,048 - INFO - django.utils.autoreload - /home/olagold-hackxx/Projects/Portfolio/backend/climate_wavers/views.py changed, reloading.
2023-11-19 10:49:31,903 - INFO - django.utils.autoreload - /home/olagold-hackxx/Projects/Portfolio/backend/climate_wavers/views.py changed, reloading.
2023-11-19 10:49:49,355 - ERROR - django.request - Internal Server Error: /api/v1/backend/posts/6690a49a-bfc6-46ea-8560-be0a4516c380/comment
Traceback (most recent call last):
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "/home/olagold-hackxx/Projects/Portfolio/backend/climate_wavers/views.py", line 680, in comment
    serializer["subcomment_count"] = subcomment_count
TypeError: 'ListSerializer' object does not support item assignment
2023-11-19 10:49:49,361 - ERROR - django.request - Internal Server Error: /api/v1/backend/posts/6690a49a-bfc6-46ea-8560-be0a4516c380/comment
Traceback (most recent call last):
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "/home/olagold-hackxx/Projects/Portfolio/backend/climate_wavers/views.py", line 680, in comment
    serializer["subcomment_count"] = subcomment_count
TypeError: 'ListSerializer' object does not support item assignment
2023-11-19 10:52:15,377 - INFO - django.utils.autoreload - /home/olagold-hackxx/Projects/Portfolio/backend/climate_wavers/serializers.py changed, reloading.
2023-11-19 10:53:31,504 - INFO - django.utils.autoreload - /home/olagold-hackxx/Projects/Portfolio/backend/climate_wavers/views.py changed, reloading.
2023-11-19 10:57:00,752 - ERROR - django.request - Internal Server Error: /api/v1/backend/posts/undefined/comment
Traceback (most recent call last):
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "/home/olagold-hackxx/Projects/Portfolio/backend/climate_wavers/views.py", line 660, in comment
    post = Post.objects.get(id=post_id)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/db/models/query.py", line 435, in get
    raise self.model.DoesNotExist(
climate_wavers.models.Post.DoesNotExist: Post matching query does not exist.
2023-11-19 12:03:32,507 - WARNING - django.request - Unauthorized: /api/v1/backend/
2023-11-19 12:03:32,508 - WARNING - django.request - Unauthorized: /api/v1/backend/
2023-11-19 12:03:41,029 - WARNING - django.request - Unauthorized: /api/v1/backend/community
2023-11-19 12:03:41,033 - WARNING - django.request - Unauthorized: /api/v1/backend/community
2023-11-19 12:03:42,691 - WARNING - django.request - Unauthorized: /api/v1/backend/
2023-11-19 12:03:42,692 - WARNING - django.request - Unauthorized: /api/v1/backend/
2023-11-19 12:03:46,080 - WARNING - django.request - Unauthorized: /api/v1/backend/
2023-11-19 12:03:46,094 - WARNING - django.request - Unauthorized: /api/v1/backend/
2023-11-19 12:19:10,315 - ERROR - climatewavers - 'Post' object has no attribute 'comment_count'
2023-11-19 12:19:10,317 - WARNING - django.request - Bad Request: /api/v1/backend/posts/581d1274-4044-468c-bb37-d9db71ec4c78/comment
2023-11-19 13:14:34,475 - ERROR - climatewavers - Follower matching query does not exist.
2023-11-19 13:14:54,004 - ERROR - climatewavers - Follower matching query does not exist.
2023-11-19 13:20:38,406 - ERROR - climatewavers - Follower matching query does not exist.
2023-11-19 13:26:26,408 - ERROR - climatewavers - Follower matching query does not exist.
2023-11-19 13:27:25,876 - ERROR - climatewavers - Follower matching query does not exist.
2023-11-19 13:27:30,953 - ERROR - climatewavers - Follower matching query does not exist.
2023-11-19 13:28:26,174 - ERROR - climatewavers - Follower matching query does not exist.
2023-11-19 13:34:32,376 - ERROR - climatewavers - Follower matching query does not exist.
2023-11-19 13:34:33,303 - ERROR - climatewavers - Follower matching query does not exist.
2023-11-19 13:35:09,546 - ERROR - climatewavers - Follower matching query does not exist.
2023-11-19 13:35:37,116 - ERROR - climatewavers - Follower matching query does not exist.
2023-11-19 13:36:13,305 - INFO - django.utils.autoreload - /home/olagold-hackxx/Projects/Portfolio/backend/climate_wavers/serializers.py changed, reloading.
2023-11-19 13:40:04,018 - ERROR - climatewavers - Follower matching query does not exist.
2023-11-19 13:41:03,991 - ERROR - climatewavers - Follower matching query does not exist.
2023-11-19 13:54:08,855 - INFO - django.utils.autoreload - /home/olagold-hackxx/Projects/Portfolio/backend/climate_wavers/urls.py changed, reloading.
2023-11-19 13:55:46,427 - INFO - django.utils.autoreload - /home/olagold-hackxx/Projects/Portfolio/backend/climate_wavers/views.py changed, reloading.
2023-11-19 13:56:48,428 - INFO - django.utils.autoreload - /home/olagold-hackxx/Projects/Portfolio/backend/climate_wavers/views.py changed, reloading.
2023-11-19 14:01:21,755 - WARNING - django.request - Method Not Allowed: /api/v1/backend/6690a49a-bfc6-46ea-8560-be0a4516c380/unfollow
2023-11-19 14:26:28,423 - ERROR - climatewavers - Follower matching query does not exist.
2023-11-19 14:26:36,862 - ERROR - climatewavers - Follower matching query does not exist.
2023-11-19 17:13:14,888 - INFO - django.utils.autoreload - /home/olagold-hackxx/Projects/Portfolio/backend/climate_wavers/views.py changed, reloading.
2023-11-19 17:13:58,360 - WARNING - django.request - Method Not Allowed: /api/v1/backend/posts/6690a49a-bfc6-46ea-8560-be0a4516c380/unlike
2023-11-19 17:14:01,120 - WARNING - django.request - Method Not Allowed: /api/v1/backend/posts/6690a49a-bfc6-46ea-8560-be0a4516c380/unlike
2023-11-19 17:14:04,052 - WARNING - django.request - Method Not Allowed: /api/v1/backend/posts/6690a49a-bfc6-46ea-8560-be0a4516c380/save
2023-11-19 17:15:21,279 - INFO - django.utils.autoreload - /home/olagold-hackxx/Projects/Portfolio/backend/climate_wavers/views.py changed, reloading.
2023-11-19 17:15:47,903 - ERROR - django.request - Internal Server Error: /api/v1/backend/1153ee4f-8020-4e78-a9d0-f685b530f017/unfollow
Traceback (most recent call last):
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "/home/olagold-hackxx/Projects/Portfolio/backend/climate_wavers/views.py", line 639, in unfollow
    following = User.objects.get(id=user_id)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/db/models/query.py", line 435, in get
    raise self.model.DoesNotExist(
climate_wavers.models.User.DoesNotExist: User matching query does not exist.
2023-11-19 17:16:46,423 - ERROR - django.request - Internal Server Error: /api/v1/backend/1153ee4f-8020-4e78-a9d0-f685b530f017/follow
Traceback (most recent call last):
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "/home/olagold-hackxx/Projects/Portfolio/backend/climate_wavers/views.py", line 621, in follow
    following = User.objects.get(id=user_id)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/db/models/query.py", line 435, in get
    raise self.model.DoesNotExist(
climate_wavers.models.User.DoesNotExist: User matching query does not exist.
2023-11-19 19:23:41,195 - INFO - django.utils.autoreload - /home/olagold-hackxx/Projects/Portfolio/backend/climate_wavers/views.py changed, reloading.
2023-11-19 19:27:31,332 - INFO - django.utils.autoreload - /home/olagold-hackxx/Projects/Portfolio/backend/climate_wavers/views.py changed, reloading.
2023-11-19 19:28:11,364 - INFO - django.utils.autoreload - /home/olagold-hackxx/Projects/Portfolio/backend/climate_wavers/urls.py changed, reloading.
2023-11-19 19:28:26,493 - INFO - django.utils.autoreload - /home/olagold-hackxx/Projects/Portfolio/backend/climate_wavers/urls.py changed, reloading.
2023-11-19 19:31:11,863 - ERROR - django.request - Internal Server Error: /api/v1/backend/waverx
Traceback (most recent call last):
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "/home/olagold-hackxx/Projects/Portfolio/backend/climate_wavers/views.py", line 54, in ai_tweet
    happening_posts = Post.objects.filter(
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/db/models/query.py", line 941, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/db/models/query.py", line 961, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/db/models/query.py", line 968, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1393, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1412, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1286, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1112, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1539, in names_to_path
    raise FieldError("Cannot resolve keyword '%s' into field. "
django.core.exceptions.FieldError: Cannot resolve keyword 'username' into field. Choices are: category, comments, content_image, content_text, date_created, id, likers, savers, user, user_id
2023-11-19 19:31:11,865 - ERROR - django.request - Internal Server Error: /api/v1/backend/waverx
Traceback (most recent call last):
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "/home/olagold-hackxx/Projects/Portfolio/backend/climate_wavers/views.py", line 54, in ai_tweet
    happening_posts = Post.objects.filter(
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/db/models/query.py", line 941, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/db/models/query.py", line 961, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/db/models/query.py", line 968, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1393, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1412, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1286, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1112, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1539, in names_to_path
    raise FieldError("Cannot resolve keyword '%s' into field. "
django.core.exceptions.FieldError: Cannot resolve keyword 'username' into field. Choices are: category, comments, content_image, content_text, date_created, id, likers, savers, user, user_id
2023-11-19 19:33:51,405 - ERROR - django.request - Internal Server Error: /api/v1/backend/waverx
Traceback (most recent call last):
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "/home/olagold-hackxx/Projects/Portfolio/backend/climate_wavers/views.py", line 54, in ai_tweet
    happening_posts = Post.objects.filter(
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/db/models/query.py", line 941, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/db/models/query.py", line 961, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/db/models/query.py", line 968, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1393, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1412, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1286, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1112, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1539, in names_to_path
    raise FieldError("Cannot resolve keyword '%s' into field. "
django.core.exceptions.FieldError: Cannot resolve keyword 'username' into field. Choices are: category, comments, content_image, content_text, date_created, id, likers, savers, user, user_id
2023-11-19 19:33:51,461 - ERROR - django.request - Internal Server Error: /api/v1/backend/waverx
Traceback (most recent call last):
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "/home/olagold-hackxx/Projects/Portfolio/backend/climate_wavers/views.py", line 54, in ai_tweet
    happening_posts = Post.objects.filter(
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/db/models/query.py", line 941, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/db/models/query.py", line 961, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/db/models/query.py", line 968, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1393, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1412, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1286, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1112, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1539, in names_to_path
    raise FieldError("Cannot resolve keyword '%s' into field. "
django.core.exceptions.FieldError: Cannot resolve keyword 'username' into field. Choices are: category, comments, content_image, content_text, date_created, id, likers, savers, user, user_id
2023-11-19 19:34:08,896 - ERROR - django.request - Internal Server Error: /api/v1/backend/waverx
Traceback (most recent call last):
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "/home/olagold-hackxx/Projects/Portfolio/backend/climate_wavers/views.py", line 54, in ai_tweet
    happening_posts = Post.objects.filter(
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/db/models/query.py", line 941, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/db/models/query.py", line 961, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/db/models/query.py", line 968, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1393, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1412, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1286, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1112, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1539, in names_to_path
    raise FieldError("Cannot resolve keyword '%s' into field. "
django.core.exceptions.FieldError: Cannot resolve keyword 'username' into field. Choices are: category, comments, content_image, content_text, date_created, id, likers, savers, user, user_id
2023-11-19 19:34:08,949 - ERROR - django.request - Internal Server Error: /api/v1/backend/waverx
Traceback (most recent call last):
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "/home/olagold-hackxx/Projects/Portfolio/backend/climate_wavers/views.py", line 54, in ai_tweet
    happening_posts = Post.objects.filter(
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/db/models/query.py", line 941, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/db/models/query.py", line 961, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/db/models/query.py", line 968, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1393, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1412, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1286, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1112, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1539, in names_to_path
    raise FieldError("Cannot resolve keyword '%s' into field. "
django.core.exceptions.FieldError: Cannot resolve keyword 'username' into field. Choices are: category, comments, content_image, content_text, date_created, id, likers, savers, user, user_id
2023-11-19 19:34:25,354 - ERROR - django.request - Internal Server Error: /api/v1/backend/waverx
Traceback (most recent call last):
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "/home/olagold-hackxx/Projects/Portfolio/backend/climate_wavers/views.py", line 54, in ai_tweet
    happening_posts = Post.objects.filter(
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/db/models/query.py", line 941, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/db/models/query.py", line 961, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/db/models/query.py", line 968, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1393, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1412, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1286, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1112, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1539, in names_to_path
    raise FieldError("Cannot resolve keyword '%s' into field. "
django.core.exceptions.FieldError: Cannot resolve keyword 'username' into field. Choices are: category, comments, content_image, content_text, date_created, id, likers, savers, user, user_id
2023-11-19 19:34:25,420 - ERROR - django.request - Internal Server Error: /api/v1/backend/waverx
Traceback (most recent call last):
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "/home/olagold-hackxx/Projects/Portfolio/backend/climate_wavers/views.py", line 54, in ai_tweet
    happening_posts = Post.objects.filter(
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/db/models/query.py", line 941, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/db/models/query.py", line 961, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/db/models/query.py", line 968, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1393, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1412, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1286, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1112, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1539, in names_to_path
    raise FieldError("Cannot resolve keyword '%s' into field. "
django.core.exceptions.FieldError: Cannot resolve keyword 'username' into field. Choices are: category, comments, content_image, content_text, date_created, id, likers, savers, user, user_id
2023-11-19 19:34:53,277 - ERROR - django.request - Internal Server Error: /api/v1/backend/waverx
Traceback (most recent call last):
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "/home/olagold-hackxx/Projects/Portfolio/backend/climate_wavers/views.py", line 54, in ai_tweet
    happening_posts = Post.objects.filter(
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/db/models/query.py", line 941, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/db/models/query.py", line 961, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/db/models/query.py", line 968, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1393, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1412, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1286, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1112, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1539, in names_to_path
    raise FieldError("Cannot resolve keyword '%s' into field. "
django.core.exceptions.FieldError: Cannot resolve keyword 'username' into field. Choices are: category, comments, content_image, content_text, date_created, id, likers, savers, user, user_id
2023-11-19 19:34:53,306 - ERROR - django.request - Internal Server Error: /api/v1/backend/waverx
Traceback (most recent call last):
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/rest_framework/decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "/home/olagold-hackxx/Projects/Portfolio/backend/climate_wavers/views.py", line 54, in ai_tweet
    happening_posts = Post.objects.filter(
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/db/models/query.py", line 941, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/db/models/query.py", line 961, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/db/models/query.py", line 968, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1393, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1412, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1286, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg)
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1112, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
  File "/home/olagold-hackxx/.local/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1539, in names_to_path
    raise FieldError("Cannot resolve keyword '%s' into field. "
django.core.exceptions.FieldError: Cannot resolve keyword 'username' into field. Choices are: category, comments, content_image, content_text, date_created, id, likers, savers, user, user_id
2023-11-19 19:37:47,554 - INFO - django.utils.autoreload - /home/olagold-hackxx/Projects/Portfolio/backend/climate_wavers/views.py changed, reloading.
2023-11-19 19:40:02,075 - INFO - django.utils.autoreload - /home/olagold-hackxx/Projects/Portfolio/backend/climate_wavers/views.py changed, reloading.
2023-11-19 20:07:29,202 - WARNING - django.request - Unauthorized: /api/v1/backend/posts/566fd5d2-a832-4a0b-afb6-b8d4a8e04b89/like
2023-11-19 20:07:33,048 - WARNING - django.request - Unauthorized: /api/v1/backend/posts/566fd5d2-a832-4a0b-afb6-b8d4a8e04b89/like
2023-11-19 20:07:41,830 - WARNING - django.request - Unauthorized: /api/v1/backend/posts/531e0dfc-8c66-4ec1-be14-10d1ac529763/like
2023-11-19 20:08:58,946 - WARNING - django.request - Unauthorized: /api/v1/backend/posts/50e225c3-1a33-49b0-857a-daa003d4dd2b/like
2023-11-19 20:09:02,082 - WARNING - django.request - Unauthorized: /api/v1/backend/posts/566fd5d2-a832-4a0b-afb6-b8d4a8e04b89/like
